complete -c asciii -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_use_subcommand" -f -a "bootstrap" -d 'set\'s up a new instance'
complete -c asciii -n "__fish_use_subcommand" -f -a "new" -d 'Rechnung erstellen'
complete -c asciii -n "__fish_use_subcommand" -f -a "list" -d 'Projekte auflisten'
complete -c asciii -n "__fish_use_subcommand" -f -a "open" -d 'Öffnet peicherverzeichniss'
complete -c asciii -n "__fish_use_subcommand" -f -a "edit" -d 'Bearbeite ein bestimmtes Projekt'
complete -c asciii -n "__fish_use_subcommand" -f -a "meta"
complete -c asciii -n "__fish_use_subcommand" -f -a "archive" -d 'Archiviere ein Project'
complete -c asciii -n "__fish_use_subcommand" -f -a "unarchive" -d 'Verschiebt ein archviertes Projekt zurück ins Arbeitsverzeichnis'
complete -c asciii -n "__fish_use_subcommand" -f -a "show" -d 'Zeige ein Projekt an'
complete -c asciii -n "__fish_use_subcommand" -f -a "set" -d 'Setzt einen Wert in einer Projekt Datei'
complete -c asciii -n "__fish_use_subcommand" -f -a "path" -d 'Zeigt den Speicherverzeichniss'
complete -c asciii -n "__fish_use_subcommand" -f -a "workspace" -d 'Open the working directory in an editor'
complete -c asciii -n "__fish_use_subcommand" -f -a "csv" -d 'Erzeugt einen CSV Report des gegebenen Jahres'
complete -c asciii -n "__fish_use_subcommand" -f -a "calendar"
complete -c asciii -n "__fish_use_subcommand" -f -a "dues" -d '(experimentel): zeige offene Posten'
complete -c asciii -n "__fish_use_subcommand" -f -a "make" -d 'Erzeuge Dokumente aus Projekten'
complete -c asciii -n "__fish_use_subcommand" -f -a "delete" -d 'Lösche ein Projekt'
complete -c asciii -n "__fish_use_subcommand" -f -a "config" -d 'Anzeigen und Editieren der '
complete -c asciii -n "__fish_use_subcommand" -f -a "shell" -d '(experimental) startet eine interaktive shell'
complete -c asciii -n "__fish_use_subcommand" -f -a "whoami" -d 'Anzeigen und Editieren der '
complete -c asciii -n "__fish_use_subcommand" -f -a "status" -d 'Zeige den Status des Arbeitsverzeichnisses'
complete -c asciii -n "__fish_use_subcommand" -f -a "pull" -d 'Pull and merge new commits from remote'
complete -c asciii -n "__fish_use_subcommand" -f -a "diff" -d 'git diff'
complete -c asciii -n "__fish_use_subcommand" -f -a "add" -d 'Fügt Ändenderungen zum git-index hinzu'
complete -c asciii -n "__fish_use_subcommand" -f -a "commit" -d 'Speichert Änderungen lokal'
complete -c asciii -n "__fish_use_subcommand" -f -a "push" -d 'Upload locally saved changes to the remote'
complete -c asciii -n "__fish_use_subcommand" -f -a "cleanup" -d 'setzt Änderungen zurück und löscht ungetrackte Datein'
complete -c asciii -n "__fish_use_subcommand" -f -a "stash" -d 'entspricht git stash'
complete -c asciii -n "__fish_use_subcommand" -f -a "pop" -d 'entspricht git pop'
complete -c asciii -n "__fish_use_subcommand" -f -a "log" -d 'Zeite Commitlog'
complete -c asciii -n "__fish_use_subcommand" -f -a "remote" -d 'Zeit Informationen über den git-remote'
complete -c asciii -n "__fish_use_subcommand" -f -a "complete" -d 'Generates completion for bash, zsh, etc'
complete -c asciii -n "__fish_use_subcommand" -f -a "version" -d 'Prints version information'
complete -c asciii -n "__fish_use_subcommand" -f -a "doc" -d 'Öffnet die Online Dokumentation, please lies sie!'
complete -c asciii -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c asciii -n "__fish_seen_subcommand_from bootstrap" -l to -d 'where to clone to'
complete -c asciii -n "__fish_seen_subcommand_from bootstrap" -s e -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from bootstrap" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from bootstrap" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from new" -s d -l date -d 'Setze das Datum eines Projekts'
complete -c asciii -n "__fish_seen_subcommand_from new" -l desc -d 'Überschreibe die Beschreibung eines Projekts'
complete -c asciii -n "__fish_seen_subcommand_from new" -s t -l template -d 'Benutze ein bestimmtes Vorlage'
complete -c asciii -n "__fish_seen_subcommand_from new" -s e -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from new" -s m -l manager -d 'Überschreibt den Projektmanager'
complete -c asciii -n "__fish_seen_subcommand_from new" -l time -d 'Setzt die Anfangszeit des Projekts manuell'
complete -c asciii -n "__fish_seen_subcommand_from new" -l time_end -d 'Setzt die Endzeit des Projekts manuell'
complete -c asciii -n "__fish_seen_subcommand_from new" -l length -d 'Überschreibt die Dauer des Events'
complete -c asciii -n "__fish_seen_subcommand_from new" -l dont -d 'Nach Erstellen nicht editieren'
complete -c asciii -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from list" -s a -l archive -d 'Liste archivierte Projtekte eines bestimmten Jahres auf. Standard: Aktuelles Jahr'
complete -c asciii -n "__fish_seen_subcommand_from list" -s y -l year -d 'Liste Projekte dieses Jahres auf, ob archiviert oder nicht'
complete -c asciii -n "__fish_seen_subcommand_from list" -s d -l details -d 'Gibt extra Felder von Projekten mit aus'
complete -c asciii -n "__fish_seen_subcommand_from list" -s f -l filter -d 'Filtert Ausgabe nach'
complete -c asciii -n "__fish_seen_subcommand_from list" -s s -l sort -d 'Sortiere Ausgabe nach: ' -r -f -a "date index name manager"
complete -c asciii -n "__fish_seen_subcommand_from list" -s e -l errors -d 'Zeigt Fehler mit an'
complete -c asciii -n "__fish_seen_subcommand_from list" -s c -l colors -d 'Liste in Farbe'
complete -c asciii -n "__fish_seen_subcommand_from list" -s n -l no-colors -d 'Zeigt Fehler mit an'
complete -c asciii -n "__fish_seen_subcommand_from list" -l simple -d 'Überschreibe Verbose Einstellung'
complete -c asciii -n "__fish_seen_subcommand_from list" -l csv -d 'Ausgabe als CSV'
complete -c asciii -n "__fish_seen_subcommand_from list" -s v -l verbose -d 'Mehr Details'
complete -c asciii -n "__fish_seen_subcommand_from list" -s A -l all -d 'Liste alle Projekte auf, alle'
complete -c asciii -n "__fish_seen_subcommand_from list" -s t -l templates -d 'Liste Vorlagen'
complete -c asciii -n "__fish_seen_subcommand_from list" -l years -d 'Liste Jahre im Archiv'
complete -c asciii -n "__fish_seen_subcommand_from list" -s p -l paths -d 'Listet Pfade zu Projektdatein'
complete -c asciii -n "__fish_seen_subcommand_from list" -s b -l broken -d 'List broken projects  without project file'
complete -c asciii -n "__fish_seen_subcommand_from list" -s C -l computed -d 'Liste mögliche berechnete Felder auf die in --details verwendet werden können.'
complete -c asciii -n "__fish_seen_subcommand_from list" -s x -l nothing -d 'Gibt nichts aus, mit Ausnahme der Angaben in --details'
complete -c asciii -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from open" -s t -l templates -d 'Zeigt Vorlagenverzeichniss'
complete -c asciii -n "__fish_seen_subcommand_from open" -s o -l output -d 'Zeigt Ausgabeverzeichniss'
complete -c asciii -n "__fish_seen_subcommand_from open" -s b -l bin -d 'Zeigt Pfad dieses Programms'
complete -c asciii -n "__fish_seen_subcommand_from open" -s i -l invoice -d 'Open invoice file'
complete -c asciii -n "__fish_seen_subcommand_from open" -l offer -d 'Open offer file'
complete -c asciii -n "__fish_seen_subcommand_from open" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from open" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s a -l archive -d 'Suche im Archiv'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s e -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s t -l template -d 'Bearbeite eine Vorlage. Können mit list --templates aufgelistet werden.'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from meta" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from meta" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from meta" -f -a "edit" -d 'Edit the meta data store'
complete -c asciii -n "__fish_seen_subcommand_from meta" -f -a "store"
complete -c asciii -n "__fish_seen_subcommand_from meta" -f -a "dump"
complete -c asciii -n "__fish_seen_subcommand_from meta" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s e -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s t -l template -d 'Bearbeite eine Vorlage. Können mit list --templates aufgelistet werden.'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from store" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from store" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from dump" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from dump" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from archive" -s y -l year -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from archive" -s F -l force -d 'Archiviere ein Projekt, selbst wenn es noch nicht vollständig ist'
complete -c asciii -n "__fish_seen_subcommand_from archive" -s a -l all -d 'Archiviere alle Projekte die archiviert werden können'
complete -c asciii -n "__fish_seen_subcommand_from archive" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from archive" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from unarchive" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from unarchive" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from show" -s d -l detail -d 'Zeigt ein bestimmtes Detail an'
complete -c asciii -n "__fish_seen_subcommand_from show" -s a -l archive -d 'Suche im Archiv'
complete -c asciii -n "__fish_seen_subcommand_from show" -s j -l json -d 'Zeige das Projekt als Json'
complete -c asciii -n "__fish_seen_subcommand_from show" -s C -l ical -d 'Zeige das Projekt als iCal'
complete -c asciii -n "__fish_seen_subcommand_from show" -l yaml -d 'Show project as raw yaml'
complete -c asciii -n "__fish_seen_subcommand_from show" -s f -l empty_fields -d 'Zeigt Felder an die automatisch gefüllt werden können'
complete -c asciii -n "__fish_seen_subcommand_from show" -s e -l errors -d 'Zeigt Fehler im Projekt'
complete -c asciii -n "__fish_seen_subcommand_from show" -s t -l template -d 'Zeigt Felder an die automatisch gefüllt werden können'
complete -c asciii -n "__fish_seen_subcommand_from show" -l files -d 'Datein in diesem Projektverzeichniss'
complete -c asciii -n "__fish_seen_subcommand_from show" -s i -l invoice -d 'Zeigt Werte an (Rechnungs Modules)'
complete -c asciii -n "__fish_seen_subcommand_from show" -s o -l offer -d 'Zeigt Werte an (Angebots Modules)'
complete -c asciii -n "__fish_seen_subcommand_from show" -s c -l csv -d 'Als CSV anzeigen'
complete -c asciii -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from set" -s a -l archive -d 'Suche im Archiv'
complete -c asciii -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from path" -s t -l templates -d 'Zeigt Vorlagenverzeichniss'
complete -c asciii -n "__fish_seen_subcommand_from path" -s o -l output -d 'Zeigt Ausgabeverzeichniss'
complete -c asciii -n "__fish_seen_subcommand_from path" -s b -l bin -d 'Zeigt Pfad dieses Programms'
complete -c asciii -n "__fish_seen_subcommand_from path" -s i -l invoice -d 'Open invoice file'
complete -c asciii -n "__fish_seen_subcommand_from path" -l offer -d 'Open offer file'
complete -c asciii -n "__fish_seen_subcommand_from path" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from path" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from workspace" -s a -l archive -d 'Open an archive instead'
complete -c asciii -n "__fish_seen_subcommand_from workspace" -s e -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from workspace" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from workspace" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from csv" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from csv" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s a -l archive -d 'Liste archivierte Projtekte eines bestimmten Jahres auf. Standard: Aktuelles Jahr'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s y -l year -d 'Liste Projekte dieses Jahres auf, ob archiviert oder nicht'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s t -l tasks -d 'Aufgaben erzeugen'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s A -l all -d 'Liste alle Projekte auf, alle'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from calendar" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from dues" -s i -l invoices -d 'Zeige unbezahlte '
complete -c asciii -n "__fish_seen_subcommand_from dues" -s w -l wages -d 'Zeige unbezahlte '
complete -c asciii -n "__fish_seen_subcommand_from dues" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from dues" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from make" -l file -d 'Manually pass a file path'
complete -c asciii -n "__fish_seen_subcommand_from make" -l output -d 'Manually pass a output folder'
complete -c asciii -n "__fish_seen_subcommand_from make" -s a -l archive -d 'Suche im Archiv'
complete -c asciii -n "__fish_seen_subcommand_from make" -s t -l template -d 'Benutze ein bestimmtes Template'
complete -c asciii -n "__fish_seen_subcommand_from make" -l force -d 'Tu es auch wenn\'s nicht geht'
complete -c asciii -n "__fish_seen_subcommand_from make" -l pdf -d 'Only create the PDF file'
complete -c asciii -n "__fish_seen_subcommand_from make" -s d -l dry -d 'Erzeuge das finale Produkte nicht'
complete -c asciii -n "__fish_seen_subcommand_from make" -l print -d 'Only prints to stdout'
complete -c asciii -n "__fish_seen_subcommand_from make" -l open -d 'Open the pdf file afterwards.'
complete -c asciii -n "__fish_seen_subcommand_from make" -l offer -d 'Erzeuge ein Angebot'
complete -c asciii -n "__fish_seen_subcommand_from make" -l invoice -d 'Erzeuge ein Angebot'
complete -c asciii -n "__fish_seen_subcommand_from make" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from make" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from delete" -s a -l archive -d 'Archivierte Projekte auflisten'
complete -c asciii -n "__fish_seen_subcommand_from delete" -s d -l dry -d 'Erzeuge das finale Produkte nicht'
complete -c asciii -n "__fish_seen_subcommand_from delete" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from delete" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from config" -l editor -d 'Überschreibt das Jahr'
complete -c asciii -n "__fish_seen_subcommand_from config" -s s -l show -d 'Anzeigen und Editieren der '
complete -c asciii -n "__fish_seen_subcommand_from config" -l set-root -d 'set the root folder in the config'
complete -c asciii -n "__fish_seen_subcommand_from config" -s e -l edit -d 'Anzeigen und Editieren der '
complete -c asciii -n "__fish_seen_subcommand_from config" -s d -l default -d 'Anzeigen und Editieren der '
complete -c asciii -n "__fish_seen_subcommand_from config" -s l -l location -d 'Show the location of the config file'
complete -c asciii -n "__fish_seen_subcommand_from config" -s i -l init -d 'Rechnung erstellen'
complete -c asciii -n "__fish_seen_subcommand_from config" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from config" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from shell" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from shell" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from whoami" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from whoami" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from pull" -l rebase -d 'git pull with --rebase'
complete -c asciii -n "__fish_seen_subcommand_from pull" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from pull" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from diff" -s a -l archive -d 'Archivierte Projekte auflisten'
complete -c asciii -n "__fish_seen_subcommand_from diff" -l staged -d 'Changes between the index and your last commit'
complete -c asciii -n "__fish_seen_subcommand_from diff" -s t -l template -d 'Vorlage'
complete -c asciii -n "__fish_seen_subcommand_from diff" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from diff" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from add" -s a -l archive -d 'Archivierte Projekte auflisten'
complete -c asciii -n "__fish_seen_subcommand_from add" -s t -l template -d 'Vorlage'
complete -c asciii -n "__fish_seen_subcommand_from add" -s A -l all -d 'Add all projects'
complete -c asciii -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from commit" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from commit" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from push" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from push" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from cleanup" -s a -l archive -d 'Archivierte Projekte auflisten'
complete -c asciii -n "__fish_seen_subcommand_from cleanup" -s t -l template -d 'Vorlage'
complete -c asciii -n "__fish_seen_subcommand_from cleanup" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from cleanup" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from stash" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from stash" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from pop" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from pop" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from log" -s a -l archive -d 'Archivierte Projekte auflisten'
complete -c asciii -n "__fish_seen_subcommand_from log" -s t -l template -d 'Vorlage'
complete -c asciii -n "__fish_seen_subcommand_from log" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from log" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from remote" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from remote" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from complete" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from complete" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from version" -s v -l verbose -d 'show also build information'
complete -c asciii -n "__fish_seen_subcommand_from version" -l json -d 'show verbose version as json'
complete -c asciii -n "__fish_seen_subcommand_from version" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from version" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from doc" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from doc" -s V -l version -d 'Prints version information'
complete -c asciii -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c asciii -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
